version: '3'
services:  
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=doggr
      - POSTGRES_PASSWORD=doggr
      - POSTGRES_DB=doggr
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U doggr"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=doggr
      - DB_USER=doggr
      - DB_PASS=doggr
      - HOST=0.0.0.0
      - PORT=8080
      - PASSWORD=password
      - NODE_ENV=development
      - AUTH_SECRET=supersecret219340818092358
      - GOOGLE_CLIENT_ID=ENTER SECRET
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    container_name: frontend
    build: ./frontend/
    restart: always
    ports:
      - "88:80"
    environment:
      - API_HOST=backend
      - PORT=8080
      - REACT_APP_GOOGLE_CLIENT_ID=ENTER SECRET

volumes:
  db:
    driver: local
